apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Tj5OlDhu48Q+CZahc7aFqErNoGw=,iv:lziYVV6KkqcSkY7zZoa+nJGVybbVb02rD5R+oUKH6R0=,tag:evBrbm+pWpPJguH0gtoDRw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:iCDa0wXCuvZ0CfSXWWVYIUFoSN3Tg3g3gyW3X7gHikQ2D8fL9NvE3Q==,iv:eC4g23cXzxCxVTEadQp0TrB38w/h96jK/IYAHTV+FvQ=,tag:qDx8/OR1i8XpblCNl8I46w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbVFGeHNGN1gxUm1kaUhw
            ZDdudHVMQThHbXlIY1NpWCszVEFZWUIrNUFzCjlaRHNjU2VpUG03R1BPd2Y3cmNE
            Y3QrVE1xc1I3S0NlVTJ4SjE3MHV4QmcKLS0tIGZWQXJ0VlVmU3RUSUoxdkxUWG5Z
            cnpzNGZ1TS9Da01MOHRQcWx0d1dLL2cKGpCl6pV23XwWLL6snSUdgTI5QDtH0TJQ
            uFLLch0B/8U5mG7ERb2uVla8HiWmjeHRO4hEb6lRAu7N9eowmIJi3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T21:38:00Z"
    mac: ENC[AES256_GCM,data:AsF4m7DHIru5CGtRRi45u+SUO84w/DJWJ2izu4BwPXyNYUaIAkLAiPHum1SkMtBf1Z7cyDQwIfX9k49jr0bKDcOmio0j6aQD9zmYOaJHmC5ANsnn6va2bBpgnWdjWknm7KobUqCUT9f7a19NHNqrkAoHVIW5GwGgXa4bu2jBPx8=,iv:vcozMA1+Bb8K18GAiWV6hllJcIdLnf6Uiu6cJCXAPmA=,tag:djka2PBYpAnu9bPK8n7dpQ==,type:str]
    version: 3.13.3
