developmentApp:
  enabled: true

# Loki S3 endpoint override for dev (uses seaweedfs-dev release)
loki:
  loki:
    storage:
      s3:
        endpoint: http://seaweedfs-dev-s3.seaweedfs.svc:8333

# Configuration for the Kube-Prometheus-Stack subchart
kube-prometheus-stack:
  # Grafana configuration
  grafana:
    # Add Loki as a data source
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://monitoring-dev-loki-gateway.monitoring.svc.cluster.local
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "fake"
