{{- if .Values.argocd.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
  namespace: argocd
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
  tls:
  - hosts:
    - {{ if .Values.developmentApp.enabled }}argocd-dev{{ else }}argocd{{ end }}
{{- end }}
