{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-kube-prometheus-prometheus
                port:
                  number: 9090
  tls:
  - hosts:
    - {{ if .Values.developmentApp.enabled }}prometheus-dev{{ else }}prometheus{{ end }}
{{- end }}
