{{- if .Values.gateway.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-cluster
  namespace: tailscale
  labels:
    app.kubernetes.io/name: my-cluster
    app.kubernetes.io/part-of: tailscale
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.hostname }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-gateway
                port:
                  number: 80
{{- end }}
