{{- if .Values.vault.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-app
                port:
                  name: https
  tls:
  - hosts:
    - vault
{{- end }}