{{- if .Values.vault.enabled }}
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  name: vault-app
  namespace: vault
  argocd.argoproj.io/sync-wave: "-3"
spec:
  clientConfig:
    service:
      name: vault-app
      port: 8200
      scheme: HTTPS
    caProvider:
      type: Secret
      name: vault-tls
      key: ca.crt
      namespace: vault
  parameters:
    apiVersion: config.kubevault.com/v1alpha1
    kind: VaultServerConfiguration
    path: kubernetes
    vaultRole: vault-policy-controller
    kubernetes:
      serviceAccountName: vault
      usePodServiceAccountForCSIDriver: true
{{- end }}