{{- if .Values.vault.enabled }}
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: tailscale-policy
  namespace: vault
  argocd.argoproj.io/sync-wave: "-3"
spec:
  vaultRef:
    name: vault-app
  policyDocument: |
    path "secret/data/tailscale/*" {
      capabilities = ["read"]
    }
{{- end }}
