{{- if .Values.platformApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/tracking-id: gitops:argoproj.io/Application:argocd/tailscale
  labels:
    wave-policy: sync-only
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ if .Values.developmentApp.enabled }}dev{{ else }}main{{ end }}
    path: platform/tailscale
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
        {{- if .Values.developmentApp.enabled }}
        - values-dev.yaml
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Retry=true
{{- end }}
