{{- if .Values.velero.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: s3-egress
  namespace: velero
  annotations:
    tailscale.com/tailnet-fqdn: {{ required "s3.tailnetFqdn is required (set via CI vars S3_ENDPOINT)" .Values.s3.tailnetFqdn }}
    {{- with .Values.s3.hostname }}
    tailscale.com/hostname: {{ . }}
    {{- end }}
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
{{- end }}
