{{- if .Values.velero.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rustfs-egress
  namespace: velero
  annotations:
    tailscale.com/tailnet-fqdn: {{ .Values.rustfs.tailnetFqdn | default "rustfs.lonk-mirfak.ts.net" }}
    {{- with .Values.rustfs.hostname }}
    tailscale.com/hostname: {{ . }}
    {{- end }}
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
{{- end }}
