{{- if .Values.velero.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rustfs-egress
  namespace: velero
  annotations:
    tailscale.com/tailnet-fqdn: rustfs.lonk-mirfak.ts.net
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
{{- end }}
