{{- if .Values.seaweedfs.s3.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seaweedfs-s3
  namespace: seaweedfs
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ if .Values.developmentApp.enabled }}seaweedfs-dev-s3{{- else }}seaweedfs-s3{{- end }}
                port:
                  number: 8333
  tls:
    - hosts:
        - {{ if .Values.developmentApp.enabled }}dev-seaweedfs-s3{{- else }}seaweedfs-s3{{- end }}
{{- end }}
