{{- if .Values.seaweedfs.master.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master-tailscale
  namespace: seaweedfs
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: seaweedfs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: seaweedfs
  ports:
    - name: swfs-master
      port: 9333
      protocol: TCP
      targetPort: 9333
{{- end }}
