developmentApp:
  enabled: true

# vaultAddress points to the Vault service in the dev cluster
vaultAddress: "https://vault-dev.vault.svc:8200"

vault:
  server:
    # Persistent storage
    dataStorage:
      enabled: true
      size: 2Gi
      storageClass: ""

    auditStorage:
      enabled: true
      size: 1Gi
      storageClass: ""
