development:
  enabled: true

vault:
  server:
    # Persistent storage
    dataStorage:
      enabled: true
      size: 10Gi
      # storageClass: standard

    # Audit log storage
    auditStorage:
      enabled: true
      size: 10Gi
      # storageClass: standard
