apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin-credentials
    namespace: seaweedfs
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
stringData:
    adminUser: ENC[AES256_GCM,data:AJHcZPM=,iv:QiUG/7zOciG2sHcMpmeuDLmyrQ0KELg4gQaB6IqQOrA=,tag:RBwN7evUzTMSdRgLiy9Clg==,type:str]
    adminPassword: ENC[AES256_GCM,data:Dx2Fg+UW9QGMaGfu8wiTpVBY7gmcz7uE,iv:h5ea2R4jEC6dR/I94FYG5k0oMroPjALsNaf4GBB0VFY=,tag:e55knkJXfN0raE6dGSBHJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T0xML1o5MkVzT1IyL3FL
            YVpqSDJGbWFyU2pOUTE5MzJ6b0tzZ1lhdGxvCkt3aFNsRUtScDBiUWVIRDlnaGJI
            Qk83dFp3K1ZpR2tpYjZ2QUd0QXFQcFUKLS0tIGIyVzlqZ3AvcVBjMmgxWW0wdGRH
            R2FGWUI4OHhqallYOGpORDJ1c2FZbUkK0hU/GjVWaYsSvjFAdbZOp28/WTJt8nwy
            +2C3M5x7K1uVdM4brZbCMggntoED+jOhvkX+klyFYK1DhJO7Fb72FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T21:37:00Z"
    mac: ENC[AES256_GCM,data:Q8oHiKtezYFUj+fjbM/d/qKJU72k2jmvcA+a21tHfWmVpwANF8byith9VtZEy9lwr3HBNRhjJzWsQaDMzcus4iFq3/8zGkU73XrPT0zRzKG5ykOD+2FcPV70/NJrDhHLzQJ7Xph+CSYDlOhLQufXS3yo7vmr8XWNDP0El5l3dm8=,iv:R5i4BlIgQfGgdsI7CXtmdozZdgBQmL9Zx5hSFOcHS80=,tag:eKjhPVminjTKuZyQTzs+mw==,type:str]
    version: 3.13.3
