apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
stringData:
    admin_access_key: ENC[AES256_GCM,data:R32Bgbjh/ftrq9mMUxe4ijkgEzw=,iv:gMUKX7LwLHjhBx/JY91MqpW8f6Mw8ws/rRO4bjCMQVE=,tag:+1QcJnHl2A6JOmWQL/cbng==,type:str]
    admin_secret_key: ENC[AES256_GCM,data:74aVLcP8lzbB8wu9SkIDqUb72V3NUdjqZH2sWmHskrHbz/uwrRbAjg==,iv:Vy4j6fEusMTum5TUXviwgcn9O1mN+U0JXprduno++WQ=,tag:s0ADYDCh3LcCC3EPaCfqZA==,type:str]
    read_access_key: ENC[AES256_GCM,data:yHdb75WyrlFIYnd1iU1QdMqDZkE=,iv:9b1wskxFcuJ2MH+++abtwX+jGvkmEOzeyBR+xNHUXFg=,tag:9UiO3RUbD/6Ufxfa+BWMXQ==,type:str]
    read_secret_key: ENC[AES256_GCM,data:XOfZGn9d0iqWc6QAvgV+WMYrgP9YqYwRZ71Px2nVKUpFhfD5MV47GQ==,iv:lD1FtEoCfsu814ns2ROam5ObNDy7ldrHmGgWXY/k/4I=,tag:MSb23bIxQKyHTL+cMvSs5Q==,type:str]
    seaweedfs_s3_config: ENC[AES256_GCM,data:aMibpusiImYg2gAnfhpE8ywtXYbJC5zbbQPHbRUruD54If3iTZ4XOMUv8YPDmUrBIFcTRIL891c8sk9w6zRh6mK5Y6F9B2f6OvTBqZgCbriPw8aINI6V1XghJfnt1YVgnTfr7rE+bSMxTeufFTF+H7d2VrZNs8UY0KDFGPbKupsypUDB3Q0c9W818oePAW204q7+nWR4HiXKoWB6fwucx6ex+B6pO1/tUmq+6pND8Y9wF2lQNZi8HBTM37E2CQrOJ7jvpD5uXTEN1Di3+zOf5dfzpHO5SGXjib7bf6VaQVnQDtaiY5wmvw1oRHNiBC5x2YcIf0dflOjuub2dZtsK1gvifNGyZJBTFBYhFQFnTNwhQQ/WUmSXhwzI6dnA6uCIjiGkks6n8oEhqPJc66PGiXl20geKT2q6c3AMmYeYcDgLOiqdJq6hG4c=,iv:1jVOAEmQhIgyvCr6xEdbfq7ZFDcgoxn69CeYRz9/+e0=,tag:peG30uxFeQCe1oSwjPQWVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eVRKNWVob25raEVQbEwy
            Y0c2VmFid21VOTAwTDZLL0NJVlJjT1BlNnhrCmdrQjMwTldoc2dKN0FiSFpTeGhE
            OGY2NlA3VlRxVEhVL3VVMmYvSStNaUUKLS0tIEdIQWJ0UVpPRHVTZ3hNVFB4TXpX
            VVBXT1J5WTNFTysxZHRVRnNHa2Z0UHMK3WiqCFKC+fS+Z1rIVCtTkSHM/cTZPfTo
            DUb5EXfCnJiIYUNtJp8SfhvVTKA8LkBT8iere89MfPA4Spt4GOn47w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T21:40:34Z"
    mac: ENC[AES256_GCM,data:yYn28Y7Vf+IacGBNSTEFE7wlZUtFvtyIYuel/J0/Q5oRYe5diUlnl1sW0snaJJLqjpZMtEg+f0TjAoSCOleyCJkHhteCL5snLwQLVH5Ifo8Y2T2NK+O9UFsLCyzxfwvigddwmQ/zWoU2KlhqJW7RGm/5MJ3/pcjqNcvDcxaUWKQ=,iv:LVXoRl7QidwMSmOoZ2iClybHi3Hqh74K69B5zyI3srE=,tag:JgwNN9Sf+sNUHo1OZR5pOQ==,type:str]
    version: 3.13.3
