{{- if .Values.vault.enabled }}
apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: kv-secret-engine
  namespace: vault
  argocd.argoproj.io/sync-wave: "-3"
spec:
  vaultRef:
    name: vault-app
  path: secret
  type: kv
  secretEngineConfig:
    kubernetes:
      serviceAccountName: vault
{{- end }}
