{{- if .Values.vault.enabled }}
apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: eso-tailscale-role
  namespace: vault
  argocd.argoproj.io/sync-wave: "-3"
spec:
  vaultRef:
    name: vault-app
  policies:
    - ref: tailscale-policy
  subjectRef:
    kubernetes:
      serviceAccountNames:
        - "external-secrets"
      serviceAccountNamespaces:
        - "external-secrets"
      ttl: "3600"
{{- end }}