apiVersion: v2
name: velero
description: "Velero backup & restore — S3 backend on RustFS (velero-homelab bucket)"
type: application
version: 1.0.0
appVersion: "1.14.1"
home: https://velero.io
icon: https://velero.io/img/Velero-logo.png
sources:
  - https://github.com/vmware-tanzu/velero
  - https://github.com/vmware-tanzu/helm-charts
maintainers:
  - name: Seom88
    url: https://github.com/Seom88
dependencies:
  - name: velero
    version: 9.0.2
    repository: https://vmware-tanzu.github.io/helm-charts
    condition: velero.enabled
