{{- if .Values.platformApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-helm-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          {{- range .Values.platformApps.helm }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
            wave: {{ .wave | quote }}
            chart: {{ .chart }}
            repoURL: {{ .repoURL }}
            version: {{ .version }}
            helmValues: {{ .values | toJson | quote }}
          {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}` }}{{- if .Values.developmentApps.enabled }}-dev{{- end }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ `{{wave}}` }}'
    spec:
      project: default
      source:
        chart: '{{ `{{chart}}` }}'
        repoURL: '{{ `{{repoURL}}` }}'
        targetRevision: '{{ `{{version}}` }}'
        helm:
          releaseName: '{{ `{{name}}` }}'
          values: '{{ `{{helmValues}}` }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{namespace}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Retry=true
{{- end }}
