{{- if .Values.platformApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-local-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          {{- range .Values.platformApps.local }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
            wave: {{ .wave | quote }}
            path: {{ .path }}
          {{- end }}
  template:
    metadata:
      name: '{{ `{{name}}` }}-app{{- if .Values.developmentApps.enabled }}-dev{{- end }}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ `{{wave}}` }}'
    spec:
      project: default
      source:
        repoURL: {{ .Values.repoURL }}
        targetRevision: {{ if .Values.developmentApps.enabled }}dev{{ else }}main{{ end }}
        path: '{{ `{{path}}` }}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - values.yaml
            {{- if .Values.developmentApps.enabled }}
            - values-dev.yaml
            {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{namespace}}` }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Retry=true
{{- end }}
