{{- if .Values.platformApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops{{- if .Values.developmentApp.enabled }}-dev{{- end }}
  namespace: argocd
  labels:
    wave-policy: sync-only
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ if .Values.developmentApp.enabled }}dev{{ else }}main{{ end }}
    path: gitops
    helm:
      valueFiles:
        - values.yaml
        {{- if .Values.developmentApp.enabled }}
        - values-dev.yaml
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}
