developmentApp:
  enabled: true

# dev overrides — mirrors platform/ts-ingress/values-dev.yaml tail before split
tailscale-operator:
  operatorConfig:
    hostname: "tailscale-operator-dev"
    defaultTags:
      - "tag:k8s-operator"
  proxyConfig:
    defaultTags: "tag:k8s"
