developmentApp:
  enabled: true

# dev overrides — hostnames for the orphan-app Ingresses in templates/infra/
tailscale-operator:
  operatorConfig:
    hostname: "tailscale-operator-dev"
    defaultTags:
      - "tag:k8s-operator"
  proxyConfig:
    defaultTags: "tag:k8s"

tailscaleIngress:
  argocd:
    hostname: argocd-dev
  hubbleUi:
    hostname: hubble-dev
