tailscale-operator:
  oauthSecretName: operator-oauth
  operatorConfig:
    hostname: "dev-tailscale-operator"
    defaultTags:
      - "tag:k8s-operator-dev"
  proxyConfig:
    defaultTags: "tag:k8s-dev"

development:
  enabled: true

# vaultAddress points to the Vault service in the dev cluster
vaultAddress: "https://vault-dev.vault.svc:8200"
