# tailscale-operator subchart values
tailscale-operator:
  enabled: true
  oauthSecretName: operator-oauth
  operatorConfig:
    hostname: "tailscale-operator"
    defaultTags:
      - "tag:k8s-operator"
  proxyConfig:
    defaultTags: "tag:k8s"
  oauth:
    clientID:
      valueFrom:
        secretKeyRef:
          name: operator-oauth
          key: client_id
    clientSecret:
      valueFrom:
        secretKeyRef:
          name: operator-oauth
          key: client_secret

development:
  enabled: false

# Ingress toggles for services to be exposed via Tailscale
argocd:
  enabled: true

vault:
  enabled: true

nginx:
  enabled: false
