# tailscale-operator subchart values
tailscale-operator:
  enabled: true
  oauthSecretName: operator-oauth
  operatorConfig:
    hostname: "tailscale-operator"

development:
  enabled: false

# Ingress toggles for services to be exposed via Tailscale
argocd:
  enabled: true

vault:
  enabled: true

nginx:
  enabled: false
