apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-credentials
  namespace: seaweedfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-seaweedfs
    kind: ClusterSecretStore
  target:
    name: seaweedfs-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        seaweedfs_s3_config: "{{ .s3_config }}"
  data:
    - secretKey: s3_config
      remoteRef:
        key: "secret/seaweedfs/s3"
        property: "s3_config"
