apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-credentials
  namespace: seaweedfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-seaweedfs
    kind: ClusterSecretStore
  target:
    name: seaweedfs-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: seaweedfs_s3_config
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None	
        key: "secret/seaweedfs/s3"
        metadataPolicy: None	
        nullBytePolicy: Ignore
        property: "s3_config"
