apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-master-data
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: longhorn
