apiVersion: v2
name: gitops
description: App-of-Apps Helm chart — manages ArgoCD Application resources only
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/Seom88/secured-gitops-tailscale-homelab
sources:
  - https://github.com/Seom88/secured-gitops-tailscale-homelab
maintainers:
  - name: Seom88
    url: https://github.com/Seom88
