apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:b9nKXBxoga/ra/8N06DGBlVi4ybcwd0A56n/RemUyT0ahC8eRI/Ke6CtCFbtnNiHCvl4sj/zf2WtXd5NrGm2+7laBjMDNbCheSY1xaExryNppY29ZZ40L3Q/zF8vRWVawMr7s2h8aWLZ/qP2xRcu,iv:OymwdJq2eTVmbVfJZmrJn2bLBRcDv2V+S2TA51djpYs=,tag:BzYz9ByUWE3Q4sXR6BX6PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R2pnM3hKYVJ3aHRxckYw
            Q1EwM1l0TU14UGpKOFFlMGt4TnBieExzaDBjCmpYa0RESnNVdnNMUjdEYUVxbXBw
            R3d3Ty9reG9TVXI3b0dMbW8vOEtVemsKLS0tICtXTnRvRTRlV2oydFF6NWR3RXFR
            V1AxSkNFS3lENUV6TUFhSEgydWRRQTAKsFHgwRc8WFA6hqo9YY7Jmfl9G1eb6J0I
            4Io5hZzXJvZtdPBTeTloUPzpVIu22mx2UiO22It93wXgRoyb9cb/mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T04:14:51Z"
    mac: ENC[AES256_GCM,data:9EY6HSRHW+l2L9kb0RoJtnJPcUb3B+B1Ozx9HNWq151SaXoEFyc4XHc6rX9k9gjfaNR8W9W9Ob4C4YopohxHg0I4QAazHjfIwsUDjERoZj518weLVa19I4gjFiD2ZUD4IIQJkxA5AWS8Ku1z0v45k3O/mSqbc8flRqVnR4VKkPY=,iv:9kt1RTJ/fk6l/XrQI0BMyMzeFC+3HqGf7pq36ToN1g8=,tag:0D8lS5wEjLWUGVOgX33zyw==,type:str]
    version: 3.13.3
