apiVersion: v2
name: cert-manager
description: cert-manager CiliumNetworkPolicies — minimal per cert-manager v1.17.2 docs
type: application
version: 1.0.0
appVersion: "v1.17.2"
home: https://cert-manager.io
sources:
  - https://github.com/cert-manager/cert-manager
maintainers:
  - name: Seom88
    url: https://github.com/Seom88
