apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-selfsigned-ca
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 87600h # 10 years
  issuerRef:
    name: vault-selfsigned-ca
    kind: Issuer
  commonName: vault.vault.svc
  dnsNames:
  - vault
  - vault.vault.svc
  - vault.vault.svc.cluster.local
  - {{ .Release.Name }}
  - {{ .Release.Name }}.vault.svc
  - {{ .Release.Name }}.vault.svc.cluster.local
  - {{ .Release.Name }}-internal
  - {{ .Release.Name }}-internal.vault.svc
  - {{ .Release.Name }}-internal.vault.svc.cluster.local
  {{- range $i := until (.Values.vault.server.ha.replicas | int) }}
  - {{ $.Release.Name }}-{{ $i }}.{{ $.Release.Name }}-internal
  - {{ $.Release.Name }}-{{ $i }}.{{ $.Release.Name }}-internal.vault.svc.cluster.local
  {{- end }}
  ipAddresses:
  - 127.0.0.1
  usages:
  - server auth
  - client auth