apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "https://{{ .Release.Name | replace "eso" "vault" }}.vault.svc:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: Secret
        name: vault-tls
        key: ca.crt
        namespace: vault
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
              name: "{{ .Release.Name }}-external-secrets"
              namespace: "external-secrets"
