apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wGCxI8n1r7idzUStBHRUdCjaYJ8=,iv:OHsKYpNirNIgLQoVT/YY9YgjwopHqrcrWsFnLlCSHrM=,tag:/mVlgdfZFx33l1KnCg3liA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a/qt2L5PQmoSiZuf0J064q/7hHLE59XDqbKKiA9jgvx6cAMyeNausQ==,iv:03EQHZdSKpgelBvI6kmJHVL61ryrQ3Cl60RUzJsltYk=,tag:34gu8Gzs+7oR6ODJGu6dlQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:zdxXEMZSJctmk7/5CJl/nxFrGV+CwYhhLf/pYOR25C9d,iv:9/TBE7xik9FcMIBhPPEYaT3Gl3qYmW1MsF3SIzVRi9w=,tag:9rc2nCwp+Rr7g3UF1wlldg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUVdGZ241TElmZ1dueEhu
            cHVremFoeEVWOGl4SVZSdnh0aXRScWhyUFE0CmhkdnNZRFRXRG9QaUp4N0xoQnFS
            TGJNUE5tZmpyQTZZTlo4dXRPcHdzME0KLS0tIGpRQVBNYTRjblFXTEQ5eGFnaTMv
            aGtUNDU3S044b3JNeENXak5GUDI5aXcKS5ALUEQMgGKr7MNNKMMgEu8MQi/CRaLO
            IQYqOk45iRAJ3tcLcmTrz/Rpg5LeM9EKvYdAn9Mhmzcbc03HxA9epA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T04:13:13Z"
    mac: ENC[AES256_GCM,data:KeLPKE7ep8b/TWMmq8MDIHAuZYMouBVxerYd+UlsJ+mFUTdMECiCLMHVov1zohMSnb0Yox/X7hJS4+G0cWL+vq2iR11nIOYKx5a0XtMf9rtQ5lb0eLe7LITnzmwJMtOykEpn949DsJkuVbQSEaYTwAqGbhM5emKyKwuJF0tTMhg=,iv:B8UGW7hz1SgQZCp9sow1m5IldZOe0ab3wGi+H60rrU0=,tag:v2Y3rnSHONaqAJWU6WOIcg==,type:str]
    version: 3.13.3
