apiVersion: v2
name: cloudnative-pg
description: "CloudNativePG is the Kubernetes operator that covers the full lifecycle of a highly available PostgreSQL database cluster with a primary/standby architecture, using native streaming replication."
type: application
version: 1.0.0
home: https://cloudnative-pg.io/
icon: https://raw.githubusercontent.com/cloudnative-pg/artwork/main/cloudnativepg-logo.svg
sources:
  - https://github.com/cloudnative-pg/charts
maintainers:
  - name: Seom88
    url: https://github.com/Seom88
dependencies:
  - name: cloudnative-pg
    version: 0.29.0
    repository: https://cloudnative-pg.github.io/charts
  # - name: plugin-barman-cloud
  #   version: 0.8.0
  #   repository: https://cloudnative-pg.github.io/charts
