ciliumNetworkPolicy:
  enabled: false

developmentApp:
  enabled: false

cloudnative-pg:
  crds:
    create: true
  config:
    clusterWide: true
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # Need check with monitoring
    # limits:
    #   cpu: 500m
    #   memory: 512Mi